spring:
  application:
    name: spring-boot-observation
  main:
    allow-circular-references: true
---
debug: false
---
logging:
  include-application-name: false
  pattern:
    dateformat: 22:mm:ss
---
management:
  endpoints:
    web:
      base-path: /ac
      exposure:
        include: '*'
---
management:
  observations:
    annotations:
      enabled: true
---
# 在prometheus中进行下面job的配置
#scrape_configs:
#  - job_name: "myapp_pool"
#    metrics_path: "/ac/prometheus"
#    static_configs:
#      - targets: ["localhost:8080"]    
---
#zipkin下载：https://repo1.maven.org/maven2/io/zipkin/zipkin-server/3.4.2/
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0   
