## config

## server
server:
  port: 8850

## spring
spring:
  application:
    name: demo-read-write
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      jdbc-url: "jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8\
        &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
        &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
      username: root
      password: root
    slave:
      jdbc-url: "jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8\
        &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
        &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
      username: read_user
      password: root

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.jiabin.multidatasource.read.write.sperate.practice.model.entity
