// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcprotocol/firstTest.proto

package com.jiabin.grpc.protocol.practice.grpcprotocol;

public interface QuerySomeDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcprotocol.QuerySomeDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>repeated .grpcprotocol.productInfo records = 2;</code>
   */
  java.util.List<com.jiabin.grpc.protocol.practice.grpcprotocol.productInfo> 
      getRecordsList();
  /**
   * <code>repeated .grpcprotocol.productInfo records = 2;</code>
   */
  com.jiabin.grpc.protocol.practice.grpcprotocol.productInfo getRecords(int index);
  /**
   * <code>repeated .grpcprotocol.productInfo records = 2;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .grpcprotocol.productInfo records = 2;</code>
   */
  java.util.List<? extends com.jiabin.grpc.protocol.practice.grpcprotocol.productInfoOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .grpcprotocol.productInfo records = 2;</code>
   */
  com.jiabin.grpc.protocol.practice.grpcprotocol.productInfoOrBuilder getRecordsOrBuilder(
      int index);
}
