spring:
  application:
    name: spring-boot-get_endpoints
---
logging:
  include-application-name: false
  pattern:
    dateformat: 21:mm:ss
---
logging:
  level:
    '[_org.springframework.web.servlet.HandlerMapping.Mappings]': debug
#    '[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]': trace
    '[org.springframework.aop.interceptor.PerformanceMonitorInterceptor]': trace
    '[org.springframework.web.servlet.DispatcherServlet]': TRACE
---
spring:
  mvc:
    log-request-details: true    
---
management:
  endpoints:
    web:
      base-path: /ac
      exposure:
        include:
        - mappings    
---
springdoc:
  swagger-ui:
    use-root-path: true