spring:
  application:
    name: spring-boot-redis_message
---
logging:
  include-application-name: false
  pattern:
    dateformat: 22:mm:ss
---
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123123
      database: 13
      connect-timeout: 10000
      timeout: 10000
      lettuce:
        pool:
          max-wait: -1
          max-active: 8
          max-idle: 8
          min-idle: 8
---
