spring:
  application:
    name: spring-boot-stream
---
logging:
  include-application-name: false
  pattern:
    dateformat: 22:mm:ss
---
#server:
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: 123123
#    key-store-type: JKS
#    key-alias: pack
#    key-password: 123123
