spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootpracticedb?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#对应mapper映射xml文件所在路径
#对应实体类
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiabin.mybatisplus.practice.entity