spring:
  application:
    name: dubbo-provider-client
server:
  port: 9090
dubbo:
  scan:
    base-packages: com.springboot  #用于扫描dubbo的注解
  application:
    id: dubbo-provider
    name: dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: my-reg
    address: zookeeper://localhost:2181